name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Transfers Build Folder to EC2 Instance
        uses: easingthemes/ssh-deploy@v3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_EC2_DEPLOY_PEM_KEY }}
          REMOTE_HOST: ${{ secrets.AWS_EC2_DEPLOY_IP_ADDRESS_HOST }}
          REMOTE_USER: ${{ secrets.AWS_EC2_DEPLOY_USER }}
          REMOTE_PORT: ${{ secrets.AWS_EC2_DEPLOY_PORT }}
          SOURCE: .output/
          TARGET: /home/ubuntu/habit-tracker-app/.output

      - name: Set AUTH_ORIGIN and Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_DEPLOY_IP_ADDRESS_HOST }}
          username: ${{ secrets.AWS_EC2_DEPLOY_USER }}
          key: ${{ secrets.AWS_EC2_DEPLOY_PEM_KEY }}
          port: ${{ secrets.AWS_EC2_DEPLOY_PORT }}
          script: |
            cd /home/ubuntu/habit-tracker-app

            # Ensure .env file exists
            if [ ! -f .env ]; then
              echo "Creating .env file..."
              touch .env
            fi

            # Set AUTH_ORIGIN if not already present
            if ! grep -q "AUTH_ORIGIN=" .env; then
              echo "AUTH_ORIGIN=${{ secrets.AUTH_ORIGIN }}" >> .env
            fi

            # Load environment variables
            source .env
