name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build
          echo "AUTH_ORIGIN=${{ secrets.AUTH_ORIGIN }}" > /home/ubuntu/habit-tracker-app/.env

      - name: Transfers Build Folder to EC2 Instance
        uses: easingthemes/ssh-deploy@v3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_EC2_DEPLOY_PEM_KEY }}
          REMOTE_HOST: ${{ secrets.AWS_EC2_DEPLOY_IP_ADDRESS_HOST }}
          REMOTE_USER: ${{ secrets.AWS_EC2_DEPLOY_USER }}
          REMOTE_PORT: ${{ secrets.AWS_EC2_DEPLOY_PORT }}
          SOURCE: .output/
          TARGET: /home/ubuntu/habit-tracker-app/.output
